# Generated by Django 3.0.8 on 2020-07-19 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ingredients'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ingredients',
            new_name='Ingredient',
        ),
    ]
